server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  application:
    name: toy
  profiles:
    active: local
    include:
      - openapi
      - vault
      - mysql
      - redis
      - monitoring
      - oauth
      - security