spring:
  config:
    activate:
      on-profile:
        - dev
management:
    endpoints:
        enabled-by-default: false
        web:
            exposure:
                include: "*"
    server:
        port: ${MON_PORT}
    endpoint:
        health:
            enabled: true
            show-details: always
        prometheus:
            enabled: true
        metrics:
            enabled: true
        info:
            enabled: true
    info:
        git:
            enabled: true
        os:
            enabled: true
        java:
            enabled: true
        build:
            enabled: true
server:
  tomcat:
    mbeanregistry:
      enabled: true
logging:
  config: classpath:logback-dev.xml