spring:
  config:
    activate:
      on-profile:
        - dev
        - local
minio:
  url: ${ADDRESS}:${MINIO_PORT}
  access:
    name: ${MINIO_ACCESS}
    secret: ${MINIO_SECRET}
  bucket:
    name: image
---
spring:
  config:
    activate:
      on-profile:
        - test
minio:
  url: http://localhost:9000
  access:
    name: test-access
    secret: test-secret
  bucket:
    name: test-bucket
---