spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      port: 6379
      host: localhost
---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      port: 6379
      host: localhost
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}